server:
    port: 8081
spring:
    application:
        name: department-service
    config:
        import: "optional:configserver:http://localhost:8088"
eureka:
    instance:
        hostname: localhost
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:8761/eureka/